output_file = 'codebase.txt'

[dirs]
[dirs.'.']
extensions = ['go', 'md', 'txt', 'json', 'js', 'ts']
include = ['.env.example']

[dirs.cmd]
extensions = ['go', 'md', 'txt']

[dirs.internal]
extensions = ['go', 'md', 'txt']
